
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-14
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-14
pull_requests: [{"author":{"id":"U_kgDOBfiN4g","is_bot":false,"login":"amanpdesai","name":"Aman Desai"},"headRefName":"menu-display-frontend-3","number":69,"title":"MenuItem Placeholder Page","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/69"},{"author":{"id":"U_kgDOB76BMA","is_bot":false,"login":"kev-yan","name":""},"headRefName":"review_backend_3","number":66,"title":"Implemented /api/reviews endpoint","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/66"},{"author":{"id":"MDQ6VXNlcjY2MjE4ODE3","is_bot":false,"login":"oviyaseeniraj","name":""},"headRefName":"menu-display-backend-3","number":63,"title":"Menu Display Backend 3: Modify menus endpoint and implement MenuItem database","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/63"},{"author":{"id":"U_kgDOB76BMA","is_bot":false,"login":"kev-yan","name":""},"headRefName":"review_backend_2","number":55,"title":"Implemented POST and GET endpoints for Reviews","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/55"}]
