
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-14
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-14
pull_requests: [{"author":{"id":"U_kgDOBfiN4g","is_bot":false,"login":"amanpdesai","name":"Aman Desai"},"headRefName":"home-page-frontend-1","number":51,"title":"Created fixtures, table, table tests, and table storybook","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/51"},{"author":{"id":"U_kgDOCL-YGQ","is_bot":false,"login":"rionapampati","name":""},"headRefName":"reviews-frontend-frontend1","number":50,"title":"My Reviews Placeholders (Frontend1)","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/50"}]
