
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-14
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-14
pull_requests: [{"author":{"id":"MDQ6VXNlcjY2MjE4ODE3","is_bot":false,"login":"oviyaseeniraj","name":""},"headRefName":"create_dining_commons","number":27,"title":"Created Dining Commons Base - Sets up Entity, Repository, and Controller for DiningCommons","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/27"}]
