
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-14
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-14
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"home-page-frontend-3","number":59,"title":"[STAGING] Create placeholder page for individual dining commons","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/59"},{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"home-page-frontend-3","number":58,"title":"Create placeholder page for individual dining commons","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/58"},{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"home-page-backend-1","number":57,"title":"[STAGING] Create a DiningCommonsService and related controller method for fetching the names of all dining commons","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/57"},{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"home-page-backend-1","number":56,"title":"Create a DiningCommonsService and related controller method for fetching the names of all dining commons","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/56"},{"author":{"id":"U_kgDOB76BMA","is_bot":false,"login":"kev-yan","name":""},"headRefName":"review_backend_2","number":55,"title":"Implemented POST and GET endpoints for Reviews","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/55"},{"author":{"id":"U_kgDOB76BMA","is_bot":false,"login":"kev-yan","name":""},"headRefName":"review_backend_1","number":53,"title":"Implemented database for reviews","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/53"},{"author":{"id":"U_kgDOCL-YGQ","is_bot":false,"login":"rionapampati","name":""},"headRefName":"reviews-frontend-frontend1","number":52,"title":"Created placeholder page for MyReviews - Reviews Frontend 1","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/52"},{"author":{"id":"U_kgDOBfiN4g","is_bot":false,"login":"amanpdesai","name":"Aman Desai"},"headRefName":"home-page-frontend-1","number":51,"title":"Created fixtures, table, table tests, and table storybook","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-14/pull/51"}]
